[package]
name = "benwis_leptos"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.70"
console_log = "1.0.0"
rand = { version = "0.8.5", features = ["min_const_gen"], optional = true }
rand_core = { version = "0.6.4", features = ["std"], optional=true }
console_error_panic_hook = "0.1.7"
futures = "0.3.27"
cfg-if = "1.0.0"
# leptos = { git="https://github.com/leptos-rs/leptos", branch="redirect-fix", default-features = false, features = [
# 	"serde",
# ] }
# leptos_meta = { git="https://github.com/leptos-rs/leptos", branch="redirect-fix", default-features = false }
# leptos_axum = { git="https://github.com/leptos-rs/leptos", branch="redirect-fix", optional = true }
# leptos_router = {  git="https://github.com/leptos-rs/leptos", branch="redirect-fix", default-features = false }
# leptos = { git="https://github.com/benwis/leptos", branch="deferred-resources", default-features = false, features = [
# 	"serde",
# ] }
# leptos_meta = { git="https://github.com/benwis/leptos", branch="deferred-resources", default-features = false }
# leptos_axum = { git="https://github.com/benwis/leptos", branch="deferred-resources", optional = true }
# leptos_router = {  git="https://github.com/benwis/leptos", branch="deferred-resources", default-features = false }
leptos = { path="../leptos/leptos", default-features = false, features = [
	"serde",
] }
leptos_meta = { path="../leptos/meta", default-features = false }
leptos_axum = { path="../leptos/integrations/axum", optional = true }
leptos_router = {  path="../leptos/router", default-features = false }
log = "0.4.17"
simple_logger = "4.1.0"
serde = { version = "1.0.158", features = ["derive"] }
axum = { version = "0.6.11", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4.0", features = ["compression-gzip", "fs"], optional=true }
tokio = { version = "1.26.0", features = ["full"], optional = true }
http = "0.2.9"
sqlx = { version = "0.6.2", features = [
	"runtime-tokio-rustls",
	"sqlite",
], optional = true }
thiserror = "1.0.40"
wasm-bindgen = "0.2.84"
axum_sessions_auth = { version = "7.0.0", features = [
	"sqlite-rustls",
], optional = true }
axum_database_sessions = { version = "7.0.0", features = [
	"sqlite-rustls",
], optional = true }
argon2 = {version="0.4.1", optional = true }
async-trait = { version = "0.1.67", optional = true }
miette = "5.6.0"
axum-extra = { version = "0.7.1", features = ["cookie"] }
web-sys = { version = "0.3.61", features = ["HtmlDocument"] }
femark = { version="0.1.3", optional = true }
slug = "0.1.4"
chrono = {version="0.4.24", optional=true}

[features]
default = ["csr"]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = ["dep:axum", "dep:tower", "dep:tokio","dep:tower-http", "dep:axum_sessions_auth", "dep:axum_database_sessions", "dep:async-trait", "dep:sqlx", "dep:argon2", "dep:femark", "dep:rand", "dep:rand_core", "leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "dep:leptos_axum", "dep:chrono"]

[package.metadata.cargo-all-features]
denylist = ["axum", "tower", "tower-http", "tokio", "sqlx", "leptos_axum", "femark", "chrono", "argon2","rand", "rand_core"]
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]

[profile.release]
lto = true
panic = "abort"
opt-level = 'z'
strip = true
codegen-units = 1
