# [unstable]
# build-std = ["std", "panic_abort", "core", "alloc"]
# build-std-features = ["panic_immediate_abort"]
build-std = ["std", "core", "alloc"]
# build-std-features = ["panic_immediate_abort"]
